### **Vehicle Sale Price Prediction**

In [1]:
import pandas as pd
import numpy as np

In [2]:
car = pd.read_csv("/content/Files/vehicle_data.csv")

In [3]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 798 entries, 0 to 797
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           798 non-null    object
 1   year           798 non-null    int64
 2   selling_price  798 non-null    int64
 3   km_driven      798 non-null    int64
 4   fuel           798 non-null    object
dtypes: int64(3), object(2)
memory usage: 31.3+ KB

In [4]:
car.head()

                       name  year  selling_price  km_driven    fuel
0             Maruti 800 AC  2007          60000      70000  Petrol
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel
3    Datsun RediGO T Option  2017         250000      46000  Petrol
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel

In [5]:
car.head(20)

                               name  year  selling_price  km_driven    fuel
0                     Maruti 800 AC  2007          60000      70000  Petrol
1          Maruti Wagon R LXI Minor  2007         135000      50000  Petrol
2              Hyundai Verna 1.6 SX  2012         600000     100000  Diesel
3            Datsun RediGO T Option  2017         250000      46000  Petrol
4             Honda Amaze VX i-DTEC  2014         450000     141000  Diesel
5              Maruti Alto LX BSIII  2007         140000     125000  Petrol
6         Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol
7          Tata Indigo Grand Petrol  2014         240000      60000  Petrol
8          Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol
9          Maruti Celerio Green VXI  2017         365000      78000     CNG
10          Chevrolet Sail 1.2 Base  2015         260000      35000  Petrol
11         Tata Indigo Grand Petrol  2014         250000     100000  Petrol
12  Toyota Corolla Altis 1.8 VL CVT  2018        1650000      25000  Petrol
13                    Maruti 800 AC  2007          60000      70000  Petrol
14         Maruti Wagon R LXI Minor  2007         135000      50000  Petrol
15             Hyundai Verna 1.6 SX  2012         600000     100000  Diesel
16           Datsun RediGO T Option  2017         250000      46000  Petrol
17            Honda Amaze VX i-DTEC  2014         450000     141000  Diesel
18             Maruti Alto LX BSIII  2007         140000     125000  Petrol
19        Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [13]:
car.shape

(798, 5)

In [7]:
car.shape

(798, 5)

In [8]:
car = car.reset_index(drop = True)

In [10]:
car.describe()

              year  selling_price      km_driven
count   798.000000   7.980000e+02     798.000000
mean   2013.239348   5.611441e+05   65064.304511
std       4.038597   6.894463e+05   46570.318785
min    1995.000000   4.000000e+04    1000.000000
25%    2011.000000   2.250000e+05   30319.750000
50%    2014.000000   3.900000e+05   58500.000000
75%    2017.000000   6.250000e+05   90000.000000
max    2020.000000   8.150000e+06  560000.000000

In [11]:
car['selling_price'] < 700000

0       True
1       True
2       True
3       True
4       True
       ...
793     True
794     True
795     True
796    False
797     True
Name: selling_price, Length: 798, dtype: bool

In [14]:
x = car[['name', 'year', 'km_driven', 'fuel']]
y = car['selling_price']

In [15]:
x

                                 name  year  km_driven    fuel
0                       Maruti 800 AC  2007      70000  Petrol
1            Maruti Wagon R LXI Minor  2007      50000  Petrol
2                Hyundai Verna 1.6 SX  2012     100000  Diesel
3              Datsun RediGO T Option  2017      46000  Petrol
4               Honda Amaze VX i-DTEC  2014     141000  Diesel
..                                ...   ...        ...     ...
793           Maruti Ciaz 1.4 AT Zeta  2017      40000  Petrol
794           Mahindra Scorpio S4 4WD  2015      60000  Diesel
795                Mahindra Quanto C8  2013      25000  Diesel
796  Hyundai Verna CRDi 1.6 SX Option  2018      26430  Diesel
797          Maruti Swift 1.3 VXI ABS  2015      24600  Petrol

[798 rows x 4 columns]

In [16]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
        ...
793     500000
794     600000
795     300000
796    1150000
797     475000
Name: selling_price, Length: 798, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
from sklearn.compose import make_column_transformer

In [24]:
ohe = OneHotEncoder()
ohe.fit(x[['name', 'fuel']])

OneHotEncoder()

In [25]:
OneHotEncoder()

OneHotEncoder()

In [26]:
make_column_transformer((OneHotEncoder(categories=ohe.categories_), ['name', 'fuel']), remainder='passthrough')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['Audi A4 2.0 TDI 177 Bhp Premium Plus', 'Audi A4 3.0 TDI Quattro',
       'Audi A4 New  2.0 TDI Multitronic',
       'Audi A6 2.0 TDI  Design Edition', 'Audi A6 2.0 TDI Premium Plus',
       'Audi A8 4.2 TDI', 'Audi Q5 2.0 TDI',
       'Audi Q7 35 TDI Quattro Premium', 'BMW 3 Series 320d Luxury Line',
       'BMW 3 Series 320d Sport',...
       'Volkswagen Polo Diesel Trendline 1.2L', 'Volkswagen Polo GTI',
       'Volkswagen Polo Petrol Comfortline 1.2L',
       'Volkswagen Polo Petrol Highline 1.2L',
       'Volkswagen Vento Celeste 1.5 TDI Highline AT',
       'Volkswagen Vento Diesel Highline',
       'Volkswagen Vento Magnific 1.6 Highline',
       'Volkswagen Vento Petrol Highline AT', 'Volvo V40 D3 R Design'],
      dtype=object),
                                                           array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                 ['name', 'fuel'])])

In [27]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_), ['name', 'fuel']), remainder='passthrough')

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
lr = LinearRegression()

In [30]:
from sklearn.pipeline import make_pipeline

In [31]:
pipe = make_pipeline(column_trans, lr)

In [32]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A4 2.0 TDI 177 Bhp Premium Plus', 'Audi A4 3.0 TDI Quattro',
       'Audi A4 New  2.0 TDI Multitronic',
       'Audi A6 2.0 TDI  Design Edition', 'Audi A6 2.0 TDI Premium Plus',
       'Audi A8 4.2 TDI', 'Audi Q5 2.0 TDI',
       'Audi Q7 35 TDI Quattro Premium', 'BMW 3 Series 3...
       'Volkswagen Polo Petrol Comfortline 1.2L',
       'Volkswagen Polo Petrol Highline 1.2L',
       'Volkswagen Vento Celeste 1.5 TDI Highline AT',
       'Volkswagen Vento Diesel Highline',
       'Volkswagen Vento Magnific 1.6 Highline',
       'Volkswagen Vento Petrol Highline AT', 'Volvo V40 D3 R Design'],
      dtype=object),
                                                                            array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'fuel'])])),
                ('linearregression', LinearRegression())])

In [35]:
y_pred = pipe.predict(x_test)

In [36]:
y_pred

array([ 266049.14537243,  669131.9046016 ,  890189.63611762,
        550067.06993855,  750372.95421477,  519907.19803881,
        107262.34036307,  313110.98484036,  743138.21361597,
        745317.11426868,  309369.49742848,  487405.398521  ,
        281361.95915859,  530174.8792054 ,  716450.74254632,
       3800525.47419931,  863565.79909103,  300007.38594957,
        506158.5031184 ,  689429.30581502,  407682.41873872,
        206579.55842786,  149590.60375962,  350538.17712789,
        722923.81046138,  575835.51337456,  759908.13780048,
        842345.66177981,  760314.88266538,  304839.31856298,
        330645.38606967,   -4984.60737042,  734549.87909126,
        863502.16504798,  566886.45373031,  270658.35802424,
       1650264.26403515, 1179428.40016604,  354426.43666166,
        721603.74326114,  866142.29944845,  394388.17422341,
        197466.61243505,  234470.68725529,  297976.62157278,
        689429.30581502,  102651.89899549,  516864.03152879,
        432825.65068328,  328725.0671306 ,  803383.82337503,
        270144.09255435,  838265.34404713,  449089.0185626 ,
        358539.66768112,  550268.15677425,  841428.67593645,
        227194.81997931,  751726.54814067,  721061.78347903,
        562194.32126113,  139768.46094883,  182125.81037056,
        406147.34593907,  792616.58819762,  196903.346619  ,
        294236.10403758,  640078.19931948,  366128.90053004,
        922427.70760681,  915159.44028233,  759908.13780048,
        839916.06212656,  339275.57073301,  780179.41241385,
        552276.3009452 ,  766851.58462349,  192929.29588463,
        493726.10878889,  171701.60886093,  749343.74987353,
        796847.12141691,  720010.67052604,  762952.34314957,
        228852.15862544,  670073.7361129 ,  837673.5274308 ,
        423260.38094543,  838101.169258  ,  117527.15908486,
        820560.49242444,  906507.47171457,  206273.03141946,
        462315.05373065,  436920.12900225, 1003763.02214633,
        727345.24580985,  206589.63228033,  326482.53243484,
        474854.02213673, 4950363.66645631,  786207.15432561,
        938745.54320375,  629183.69605596,  415804.18154245,
        335206.68754778,  788258.78689221,  190942.31999494,
        772799.78474773, 2600731.26232215,  290255.21726037,
        366182.36497013,  345901.73618001,  250263.81362414,
        492527.9959389 ,  246685.83526599,  882857.7347501 ,
        857485.25824754,  850267.49265692,  368380.88314876,
         72529.09411596,  934725.34381273,  718615.04303034,
        516864.03152879,  259891.12284683,  624373.79450749,
        163113.27433623, 1389222.62930948,  414415.25521843,
        300046.15252733,  519412.56975441,  427676.00494062,
        513565.16154096,  397495.3773713 ,  249123.88766941,
        519412.56975441,  202222.01344518,  411976.58600108,
        708784.87551714,  235511.96789607,  248358.29732216,
        552276.3009452 ,  125024.95678133,  734449.54698032,
        443662.2412191 ,  412556.77981107,  246828.47981425,
        158575.55285735,  889256.08415479,  687250.40516232,
        904392.20510492,  539944.52522297,  790898.92129268,
        345586.77822509,   79373.42258231,  221429.94466355,
        747496.01492137,  340526.29760099,  707074.97166753,
        848504.39665127])

In [37]:
from sklearn.metrics import r2_score

In [38]:
r2_score(y_test, y_pred)

0.745592677565156

In [43]:
scores = []
for i in range(850):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)
    scores.append(r2_score(y_test, y_pred))

In [44]:
np.argmax(scores)

601

In [48]:
np.argmax(scores)

601

In [49]:
hello = np.argmax(scores)

In [50]:
hello

601

In [51]:
scores[hello]

0.8270544589731799

In [55]:
pipe.predict(pd.DataFrame(columns = x_test.columns, data=np.array(['Honda Amaze VX i-DTEC', 2014, 141000, 'Diesel']).reshape(1,4)))

array([439345.64243452])

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(x_train, y_train)
y_pred = pipe.predict(x_test)
r2_score(y_test, y_pred)

0.8270544589731799

In [71]:
pipe.predict(pd.DataFrame(columns = x_test.columns, data=np.array(['Mahindra Xylo D4', 2018, 87000, 'Diesel']).reshape(1,4)))

array([878360.0741875])

In [75]:
pipe.predict(pd.DataFrame(columns = x_test.columns, data=np.array(['Ford Figo Aspire 1.2 Ti-VCT Trend', 2017, 10832, 'Petrol']).reshape(1,4)))

array([525097.04961277])